spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes:
        -id: user-service
        #          uri: http://localhost:8081
        uri: lb://USER-SERVICE
        predicates:
          - Path=/user-service/**

eureka:
  client:
    application:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/